# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210517_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
